version: '3'
services:
  web:
    image: phalconphp/ubuntu-16.04:php-7.2
    container_name: web
    volumes:
      - ./.docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/app
    ports:
      - 80:80
    restart: always
    networks:
      - app-network
  db:
    image: mysql:latest
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DBNAME}
      MYSQL_ROOT_PASSWORD: ${DBPASS}
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - app-network
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  dbdata:
    driver: local